# Generated by Django 4.1.4 on 2022-12-31 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item_name', models.CharField(max_length=70)),
                ('Total_Stock_In_KG', models.CharField(max_length=70)),
                ('Price_Per_KG', models.CharField(max_length=70)),
            ],
        ),
    ]
